# Generated by Django 4.0.5 on 2022-06-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(default=1000),
        ),
    ]
